language: node_js
node_js:
  - "12"
notifications:
  email:
    recipients:
      - jannik.hollenbach@iteratec.com
    on_success: never
    on_failure: always
services:
  - docker
env:
  - version=latest
  - version=unstable
script:
  - if [ "$version" == "latest" ]; then cp test/.env.stable.test .env; fi
  - if [ "$version" == "unstable" ]; then cp test/.env.stable.test .env; fi
  - docker-compose -f docker-compose.yml -f docker-compose.demo.yml up -d engine camundadb bodgeit juice-shop nginx unsafe-https old-wordpress ssh-service scanner-infrastructure-nmap scanner-webapplication-arachni scanner-webapplication-zap scanner-infrastructure-amass scanner-infrastructure-sslyze scanner-webserver-nikto scanner-infrastructure-ssh scanner-cms-wpscan scanner-infrastructure-ncrack
  - cd test
  - npm ci
  - npm test -- --verbose --forceExit
after_failure:
  - docker ps -a
  - docker-compose logs engine
  - docker-compose logs scanner-webapplication-zap
  - docker-compose logs scanner-webapplication-arachni
  - docker-compose logs scanner-infrastructure-amass
  - docker-compose logs scanner-infrastructure-nmap
  - docker-compose logs scanner-infrastructure-sslyze
  - docker-compose logs scanner-infrastructure-ssh
  - docker-compose logs scanner-infrastructure-ncrack
  - docker-compose logs scanner-webserver-nikto
  - docker-compose logs scanner-cms-wpscan
