version: "2.1"
services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
    networks:
      - frontend
  bodgeit:
    image: securecodebox/bodgeit
    ports:
      - 8081:8080
    networks:
      - frontend
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 8111:80
    networks:
      - frontend
  old-wordpress:
    image: securecodebox/old-wordpress:4.0
    restart: always
    ports:
      - 8000:80
    networks:
      - frontend
  ssh-service:
    image: securecodebox/dummy-ssh
    networks:
      - frontend
  unsafe-https:
    image: securecodebox/unsafe-https
    networks:
      - frontend
